# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionservice', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.IntegerField(max_length=200),
        ),
    ]
