# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionservice', '0003_auto_20161226_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='isadmin',
        ),
    ]
