# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionservice', '0004_auto_20161226_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
