# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionservice', '0005_auto_20161226_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.IntegerField(default=0),
        ),
    ]
