# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionservice', '0008_auto_20161227_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='test_time',
        ),
    ]
