# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionservice', '0011_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
        migrations.RemoveField(
            model_name='test',
            name='time',
        ),
        migrations.AddField(
            model_name='test',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='test_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
