# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionservice', '0012_auto_20161228_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='score_value',
            field=models.IntegerField(default=0),
        ),
    ]
